FileConverter -in UPS1_50amol_R3.raw -out    UPS1_50amol_R3.mzML  -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_50amol_R2.raw -out      UPS1_50amol_R2.mzML  -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_50amol_R1.raw -out      UPS1_50amol_R1.mzML  -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_500amol_R3.raw -out     UPS1_500amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_500amol_R2.raw -out     UPS1_500amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_500amol_R1.raw -out     UPS1_500amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_5000amol_R3.raw -out    UPS1_5000amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_5000amol_R2.raw -out    UPS1_5000amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_5000amol_R1.raw -out    UPS1_5000amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_50000amol_R3.raw -out   UPS1_50000amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_50000amol_R2.raw -out   UPS1_50000amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_50000amol_R1.raw -out   UPS1_50000amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_250amol_R3.raw -out     UPS1_250amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_250amol_R2.raw -out     UPS1_250amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_250amol_R1.raw -out     UPS1_250amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_2500amol_R3.raw -out    UPS1_2500amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_2500amol_R2.raw -out    UPS1_2500amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_2500amol_R1.raw -out    UPS1_2500amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_25000amol_R3.raw -out   UPS1_25000amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_25000amol_R2.raw -out   UPS1_25000amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_25000amol_R1.raw -out   UPS1_25000amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_125amol_R3.raw -out     UPS1_125amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_125amol_R2.raw -out     UPS1_125amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_125amol_R1.raw -out     UPS1_125amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_12500amol_R3.raw -out   UPS1_12500amol_R3.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_12500amol_R2.raw -out   UPS1_12500amol_R2.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
FileConverter -in UPS1_12500amol_R1.raw -out   UPS1_12500amol_R1.mzML -ThermoRaw_executable /home/sachsenb/OpenMS/THIRDPARTY/All/ThermoRawFileParser/ThermoRawFileParser.exe
